name: Update Weather

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-weather:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Get Weather
      env:
        TEMPEST_STATION: ${{ secrets.TEMPEST_STATION }}
        TEMPEST_PUT: ${{ secrets.TEMPEST_PUT }}
      run: python .github/update-weather.py
    - name: Configure Git
      run: git config --global user.name "Jade Michael Thornton" && git config --global user.email "jade@jmthornton.net"
    - name: Commit Changes
      run: |
        git add README.md
        if git diff --cached --quiet; then
          echo "No changes"
        else
          git commit -m "update weather"
          git push
        fi
